version: '3'
services:
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD:
      MYSQL_ONETIME_PASSWORD:
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.1.0
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

volumes:
  mysql:
